# -*- encoding: utf-8 -*-

=begin
#RadioManager

#RadioManager

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "radiomanager_client/version"

Gem::Specification.new do |s|
  s.name        = "radiomanager_client"
  s.version     = "1.1.13-dev"
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Pluxbox"]
  s.email       = ["support@pluxbox.com"]
  s.homepage    = "http://pluxbox.com"
  s.summary     = "RadioManager Client"
  s.description = "Pluxbox Pluxbox RadioManager Ruby SDK"
  s.license     = "Unlicense"
  s.license     = "MIT"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
