=begin
#RadioManager

#This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for RadioManagerClient::GenreApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GenreApi' do
  before do
    # run before each test
    @api_instance = RadioManagerClient::GenreApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GenreApi' do
    it 'should create an instance of GenreApi' do
      expect(@api_instance).to be_instance_of(RadioManagerClient::GenreApi)
    end
  end

  # unit tests for get_genre_by_id
  # Get genre by id
  # Get genre by id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GenreResult]
  describe 'get_genre_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_genres
  # List all genres.
  # List all genres.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Current page *(Optional)*
  # @option opts [Integer] :limit Results per page *(Optional)*
  # @option opts [String] :order_by Field to order the results *(Optional)*
  # @option opts [String] :order_direction Direction of ordering *(Optional)*
  # @return [InlineResponse2006]
  describe 'list_genres test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
