=begin
#RadioManager

#This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for RadioManagerClient::StationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StationApi' do
  before do
    # run before each test
    @api_instance = RadioManagerClient::StationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StationApi' do
    it 'should create an instance of StationApi' do
      expect(@api_instance).to be_instance_of(RadioManagerClient::StationApi)
    end
  end

  # unit tests for get_station
  # Get own station only
  # Get own station only
  # @param [Hash] opts the optional parameters
  # @return [StationResult]
  describe 'get_station test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
