=begin
#RadioManager

#RadioManager

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for RadioManagerClient::StringApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StringApi' do
  before do
    # run before each test
    @api_instance = RadioManagerClient::StringApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StringApi' do
    it 'should create an instance of StringApi' do
      expect(@api_instance).to be_instance_of(RadioManagerClient::StringApi)
    end
  end

  # unit tests for get_strings_by_name
  # Get Strings (formatted)
  # Get Strings (formatted)
  # @param name Name of Strings **(Required)**
  # @param full_model Full model or content only **(Required)**
  # @param [Hash] opts the optional parameters
  # @return [TextString]
  describe 'get_strings_by_name test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
