=begin
#RadioManager

#This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for RadioManagerClient::StringApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StringApi' do
  before do
    # run before each test
    @api_instance = RadioManagerClient::StringApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StringApi' do
    it 'should create an instance of StringApi' do
      expect(@api_instance).to be_instance_of(RadioManagerClient::StringApi)
    end
  end

  # unit tests for get_strings_by_name
  # Get Strings (formatted)
  # Get RadioText/DAB String for publication based on String Templates
  # @param name Name of String Template **(Required)**
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :full_model Full model or content only **(Optional)**
  # @return [TextString]
  describe 'get_strings_by_name test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
