=begin
#RadioManager

#RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RadioManagerClient::VisualSlideApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VisualSlideApi' do
  before do
    # run before each test
    @instance = RadioManagerClient::VisualSlideApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VisualSlideApi' do
    it 'should create an instance of VisualSlideApi' do
      expect(@instance).to be_instance_of(RadioManagerClient::VisualSlideApi)
    end
  end

  # unit tests for get_visual_slide
  # Get Visual Slide Image as Base64
  # Get Visual Slide Image as Base64
  # @param [Hash] opts the optional parameters
  # @return [VisualResult]
  describe 'get_visual_slide test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
