=begin
#RadioManager

#This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RadioManagerClient::ProgramRelationsItemsParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RadioManagerClient::ProgramRelationsItemsParams do
  let(:instance) { RadioManagerClient::ProgramRelationsItemsParams.new }

  describe 'test an instance of ProgramRelationsItemsParams' do
    it 'should create an instance of ProgramRelationsItemsParams' do
      expect(instance).to be_instance_of(RadioManagerClient::ProgramRelationsItemsParams)
    end
  end
  describe 'test attribute "program_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
